Day 6
WDtms/flutter_internship_m pull request #4
Opened 2020-11-09 08:42 UTC by WDtms

2020-11-10 01:21 UTC, grebennikovlmax requested changes

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/cubit/branch/branch_cubit.dart
> +    final _branches = _taskRepositoryAlpha.getBranches();
Локальные перенеменные не обязательно писать через '_'

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/cubit/branch/branch_state.dart
> +  const BranchState();
Пустой конструктор не обязательно прописывать, Можно оставить просто abstract class BranchState {}

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/models/task_list.dart
> +  List<TaskModel> createNewInnerTask(int index, String value) {
Сначала поля/переменные потом методы класса.

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/pages/all_tasks.dart
> +                        return SizedBox.shrink();
const

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/pages/all_tasks.dart
> +      else {
Не обязательно писать else когда в основном if есть return. Условия если попадет в if дальше не пойдет. Можно опустить else и оставить просто return state.theme.keys.toList().first;

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/pages/all_tasks.dart
> +    else {
Здесь тоже else не нужно

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/all_tasks_page/bottom_dialog/choice_theme.dart
> +  int selectedRadio;
если только внутри класса используется _selectedRadio

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/all_tasks_page/bottom_dialog/choice_theme.dart
> +  setSelectedRadio(int value){
Возращает void, и перенеси после override методов

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/all_tasks_page/tasks_display/task_list.dart
> +  int countCompletedInnerTasks(int index){
заприватить методы с _

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/all_tasks_page/tasks_display/task_list.dart
> +      key: UniqueKey(),
Старайся использовать ValueKey или ObjectKey, у тебя же есть идентификатор таски - его и используй

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/all_tasks_page/tasks_display/task_list.dart
> +  Color checkTheme(ThemeState state) {
Заприватить

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/current_task_page/cards/date_card/my_date_card.dart
> +        margin: EdgeInsets.fromLTRB(8, 30, 8, 8),
const

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/current_task_page/cards/date_card/my_date_card.dart
> +                      Padding(
А тут нужен Row в children только 1 виджет?

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/current_task_page/cards/date_card/my_date_card.dart
> +  displayDateToComplete(TaskState state){
void и заприватить

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/current_task_page/cards/date_card/my_date_card.dart
> +        DateTime date = state.taskList[index].dateToComplete;
else тоже тут не нужен

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/current_task_page/cards/my_card.dart
> +  displayDateOfCreation(TaskState state){
Везде проставить возращаемы тип

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/current_task_page/cards/my_card.dart
> +              else {
else не нужен

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/current_task_page/cards/my_card.dart
> +                    for (int i = 0; i <state.taskList[widget.index].innerTasks.length; i++)
Может лучше через ListViewBuilder?

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/current_task_page/cards/my_card.dart
> +          margin: EdgeInsets.fromLTRB(8, 30, 8, 8),
const

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/current_task_page/cards/my_card.dart
> +  final _controller = TextEditingController();
Контроллер нужно в dispose вызывать _controller.dispose() или close() точно не помню

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/current_task_page/cards/my_card.dart
> +      return Row(
Нужен Row у детей всего 1 виджет?

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/current_task_page/cards/my_card.dart
> +    else {
не нужен else

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/current_task_page/floating_button/floating_button.dart
> +  GlobalKey key = GlobalKey();
заприватить

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/current_task_page/floating_button/floating_button.dart
> +        else {
Не нужен else

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/current_task_page/popup_appbar/popup_appbar.dart
> +          else {
Не нужен else

2020-11-10 01:21 UTC, grebennikovlmax commented on lib/views/current_task_page/popup_appbar/popup_appbar.dart
> +                else {
На одной строчке } else {

2020-11-11 11:50 UTC, WDtms commented on lib/views/current_task_page/cards/date_card/my_date_card.dart
> +                      Padding(
Далее будут добавлены иконки, пока просто функционал без визуала

2020-11-12 02:23 UTC, grebennikovlmax approved these changes

2020-11-12 02:29 UTC, merged